HW/HW/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hw1.urls')),
]

HW/hw2/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    date_registered = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Username: {self.name}, email: {self.email},  phone: {self.phone}, address: {self.address}'


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField()
    date = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return f'Product name: {self.name}, price: {self.price},  description: {self.description}, quantity: {self.quantity}'


class Order(models.Model):
    customer = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    date_ordered = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f'Customer: {self.customer.name}, products: {self.products},  date_ordered: {self.date_ordered}, total_price: {self.total_price}'

HW/hw5/models.py
from django.db import models

# Create your models here.

HW/hw4/forms.py
import datetime

from django import forms

from hw2.models import Product
class ProductFormWidget(forms.Form):

    name = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': f'введите название товара'}))
    price = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    number = forms.IntegerField(min_value=0)
    image = forms.ImageField() # <--- forms for photo

class ProductChoiceForm(forms.Form):
    products = Product.objects.all()
    product_id = forms.ChoiceField(label='prod_id', choices=[(product.id, product.name) for product in products])

class ImageForm(forms.Form):
    image = forms.ImageField()

HW/hw1/views.py
import logging
from datetime import datetime

# Create your views here.
from django.http import HttpResponse

logger = logging.getLogger(__name__)


def index(request):
    html = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Мой первый Django-сайт</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.5;
                margin: 0;
                padding: 20px;
            }


        </style>
    </head>
    <body>
        <h1>Добро пожаловать на мой первый Django-сайт!</h1>

        <h2>О сайте</h2>
        <p>Этот сайт разработан с использованием Django, мощного фреймворка для создания веб-приложений на языке Python. </p>


        <p><a href="/about"> Обо мне </a></p>
    </body>
    </html>
    """
    logger.info(f'Index page accessed: {datetime.now()}')
    return HttpResponse(html)


def about(request):
    html = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Мой первый Django-сайт</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.5;
                margin: 0;
                padding: 20px;
            }

        </style>
    </head>
    <body>

        <h1>Обо мне</h1>
        <p>Привет, меня зовут Виталий Осипов</p>

        <footer>
            <p>Привет МИР!!</p>
        </footer>
    </body>
    </html>
    """

    logger.info(f'About page accessed: {datetime.now()}')
    return HttpResponse(html)

HW/hw4/views.py
import logging
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render
from .forms import ProductFormWidget, ProductChoiceForm
from hw2.models import Product

from django.shortcuts import redirect

logger = logging.getLogger(__name__)


def product_update_form(request, product_id):

    if request.method == 'POST':
        form = ProductFormWidget(request.POST, request.FILES)
        if form.is_valid():
            # Делаем что-то с данными
            logger.info(f'Получили {form.cleaned_data=}.')
            name = form.cleaned_data.get('name')
            price = form.cleaned_data.get('price')
            description = form.cleaned_data.get('description')
            number = form.cleaned_data.get('number')

            image = request.FILES['image']
            fs = FileSystemStorage()
            fs.save(image.name, image)



            product = Product.objects.filter(pk=product_id).first()
            product.name = name
            product.price = price
            product.description = description
            product.quantity = number
            product.image = image.name

            product.save()

    else:
        form = ProductFormWidget()
    return render(request, 'hw4/product_update.html', {'form': form})

def product_update_id_form(request):
    if request.method == 'POST':
        form = ProductChoiceForm(request.POST)
        if form.is_valid():
            logger.info(f'Получили {form.cleaned_data=}.')
            prod_id = form.cleaned_data.get('product_id')
            response = redirect(f'/homework4/product_update/{prod_id}')
            return response
    else:
        form = ProductChoiceForm()
    return render(request, 'hw4/product_update_id.html', {'form': form})


def index(request):
    return render(request, "hw4/index.html")

HW/hw5/views.py
from django.shortcuts import render

# Create your views here.

HW/hw2/templates/index.html
{% extends 'hw2/base.html' %}

{% block title %}Домашнее задание 3{% endblock %}

{% block content %}
    <h1>Домашнее задание , семинар 3</h1>
    <p>Создайте шаблон для вывода всех заказов клиента и списком товаров внутри каждого заказа.</p>
    <p>добавьте в поисковой строке " user/'id' " заказчика</p>
    <br>
    <br>
    <p>Создайте шаблон, который выводит список заказанных клиентом товаров из всех его заказов с сортировкой по времени:</p>
    <p>— за последние 7 дней (неделю)</p>
    <p>— за последние 30 дней (месяц)</p>
    <p>— за последние 365 дней (год)</p>
    <p>добавьте в поисковой строке " user_sorted/'id'/'days' " заказчика</p>

Товары в списке не должны повторятся.
{% endblock %}

HW/hw2/templates/user_all_orders.html
{% extends 'hw2/base.html' %}

{% block title %}{{ user.name }}'s Orders{% endblock %}

{% block content %}
    <h2>все заказы пользователя: {{ user.name }}</h2>
    {% for order in orders %}
        <h1>order</h1>
        <p>{{ order.date_ordered }}</p>
        <p>{{ order.total_price }}</p>
                <h3>Products</h3>
                <p>{{ products.pop }}</p>

    {% endfor %}

HW/hw2/templates/user_all_product.html
{% extends 'hw2/base.html' %}

{% block title %}{{ user.name }}'s Products for last  {{ days }} days {% endblock %}

{% block content %}
    <h2>все продукты пользователя: {{ user.name }} за последние {{ days }} дней</h2>
    {% for product in product_set %}

                <p>{{ product }}</p>
    {% endfor %}
{% endblock %}

HW/hw4/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Сайт{% endblock %}</title>
    </head>
<body>
    {% block content %}
        <p>Скоро тут появится текст...</p>
    {% endblock %}
</body>
</html>

HW/hw4/templates/index.html
{% extends 'hw2/base.html' %}

{% block title %}Домашнее задание , семинар 4{% endblock %}

{% block content %}
    <h1>Домашнее задание, семинар 4</h1>
    <p>Доработаем задачу про клиентов, заказы и товары из прошлого семинара. </p>
    <p>Создайте форму для редактирования товаров в базе данных.</p>
    <br>
    <br>
    <p><a href="/homework4/product_update_id"> редактирование товаров в базе данных </a></p>


{% endblock %}

HW/hw4/templates/product_update.html
{% extends 'hw4/base.html' %}

{% block title %}Обновление карточки продукта{% endblock %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить">
</form>
{% endblock %}

HW/hw4/templates/product_update_id.html
{% extends 'hw4/base.html' %}

{% block title %}Обновление карточки продукта{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить">
</form>
{% endblock %}